version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    networks:
      - network-nginx
      - network-mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    # restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - network-mariadb

networks:
  network-nginx:
    driver: bridge
    name: network-nginx
  network-mariadb:
    driver: bridge
    name: network-mariadb
  #container
    #build
    #ports
