version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    networks:
      - network-42
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    # restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - network-42

networks:
  network-42:
    driver: bridge
    name: network-42
  #container
    #build
    #ports
