version: "3"

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        - CERT=${CERT}
        - CERT_KEY=${CERT_KEY}
    container_name: nginx
    image: nginx
    env_file: .env
    ports:
      - 443:443
    networks:
      - network-42
    volumes:
      - wordpress:/var/www/jofelipe/wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    # restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network-42

  wordpress:
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_HOST=${MYSQL_HOST}
    container_name: wordpress
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/jofelipe/wordpress
    networks:
      - network-42

networks:
  network-42:
    driver: bridge
    name: network-42

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jofelipe/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jofelipe/data/mariadb
