version: "3"

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        - CERT=${CERT}
        - CERT_KEY=${CERT_KEY}
    container_name: nginx
    image: nginx
    env_file: .env
    environment:
      - CERT=${CERT}
      - CERT_KEY=${CERT_KEY}
    ports:
      - 443:443
    networks:
      - network-42
    volumes:
      - wordpress:/var/www/jofelipe/wordpress
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    # restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - network-42
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/jofelipe/wordpress
    # volumes:
    #   - type: bind
    #     source: /home/jofelipe/data/wordpress
    #     target: /var/www/html/
    networks:
      - network-42

networks:
  network-42:
    driver: bridge
    name: network-42
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jofelipe/data/wordpress
