FROM debian:stable

RUN apt update
RUN apt install nginx -y
RUN apt install iputils-ping -y

COPY server1.conf /etc/nginx/sites-available/

RUN ln -s /etc/nginx/sites-available/server1.conf \
          /etc/nginx/sites-enabled/server1.conf


COPY script.sh /usr/bin/
RUN chmod a+x /usr/bin/script.sh && \
    ./usr/bin/script.sh
EXPOSE 443

ENTRYPOINT [ "script.sh" ]
CMD [ "nginx", "-g", "daemon off;" ]
#
# ENTRYPOINT [ "bash" ]


# RUN apt install sudo -y
# RUN ufw app list
# RUN ufw allow 'Nginx HTTP'
